In [1]:
! pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [6]:
arr=arr np.array([1,2,3,4,5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
print(arr.dtype)

int64


In [12]:
arr2 = np.array([1,2,3,4,5],dtype=np.int16)

In [17]:
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [18]:
Z=np.zeros(5)

In [19]:
Z

array([0., 0., 0., 0., 0.])

In [24]:
ar=np.arange(0,10,1)

In [25]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ran=np.random.rand(4)

In [27]:
ran

array([0.11480896, 0.89366106, 0.39762397, 0.15340434])

In [28]:
ln=np.linspace(0,100,10)

In [29]:
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [31]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])

ar2

In [32]:
o1=np.ones([5,5])

In [33]:
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
I=np.eye(5)

In [35]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
r1=np.random.rand(4,5)

In [37]:
r1

array([[0.06905912, 0.38572693, 0.81908764, 0.29314963, 0.44667002],
       [0.52511916, 0.97461127, 0.21733169, 0.63912789, 0.3888063 ],
       [0.83126752, 0.02211221, 0.15464525, 0.04550719, 0.71148101],
       [0.04674922, 0.39988012, 0.86199072, 0.3607193 , 0.90695357]])

In [38]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
print(ar.size)

10


In [41]:
print(ar2.size)

9


In [42]:
print(ar.shape)

(10,)


In [43]:
print(ar2.shape)

(3, 3)


In [44]:
ar3=np.copy(ar2)

In [45]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar3[1,2]=12
ar3[0,1]=15

In [47]:
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [48]:
ar3=np.sort(ar3,axis=0)

In [49]:
ar3

array([[ 1,  5,  3],
       [ 4,  8,  9],
       [ 7, 15, 12]])

In [50]:
ar3.sum()

np.int64(64)

In [51]:
ar3.sum(axis=0)

array([12, 28, 24])

In [54]:
ar3.sum(axis=1)

array([ 9, 21, 34])

In [55]:
ar3=np.copy(ar2)

In [66]:
ar4=np.random.rand(99)
ar4

array([9.48804773e-01, 1.41727125e-01, 8.40384975e-02, 8.85817606e-01,
       9.81650415e-01, 5.90100974e-01, 5.26600228e-01, 7.41293760e-01,
       7.14492078e-01, 2.92052421e-01, 3.89052782e-04, 7.95206396e-02,
       8.82064227e-01, 1.96242929e-01, 9.21681662e-01, 1.18891700e-01,
       4.21189585e-01, 7.59809243e-01, 9.04354607e-01, 4.41305542e-01,
       4.43464131e-01, 4.26377230e-01, 6.53037314e-01, 5.08477533e-01,
       5.83313755e-01, 2.06149312e-03, 5.19799887e-01, 7.11502494e-01,
       7.09119683e-01, 3.00014819e-01, 9.34736492e-01, 2.57136543e-01,
       6.58246798e-02, 2.04690497e-01, 2.14064568e-01, 9.94833214e-01,
       7.22786627e-01, 5.26160323e-04, 1.94791772e-01, 7.61669135e-02,
       4.20162804e-02, 6.51644223e-01, 3.56818967e-01, 8.50935422e-01,
       9.62793582e-01, 9.58079744e-01, 1.34244426e-01, 3.16905408e-01,
       9.36862274e-01, 2.62271951e-01, 3.02045618e-01, 2.89459948e-01,
       8.53958262e-02, 3.64899229e-01, 4.14603875e-01, 9.63778478e-02,
      

In [67]:
 ar4.size

99

In [68]:
ar4.reshape

<function ndarray.reshape>

In [69]:
ar4.shape

(99,)

In [70]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
ar3=ar3.T

In [72]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [73]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
ar=np.append(ar,10)

In [77]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
ar=np.delete(ar,6,axis=0)

In [79]:
ar=np.insert(ar,6,6)

In [80]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [89]:
ar4=np.concatenate((ar2,ar3),axis=0)
print(ar4)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 4 7]
 [2 5 8]
 [3 6 9]]


In [90]:
ar5=np.concatenate((ar2,ar3),axis=0)
ar5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

NameError: name 'ar6' is not defined